### ISSUE TITLE
Url encoded twice

### ISSUE THREAD

**Issue by mrandi** [fazendadosoftware/vue-cli-plugin-leanix#5]
Hi, 
it seems that the localhosturl is encoded twice here: https://github.com/fazendadosoftware/vue-cli-plugin-leanix/blob/master/commands/LeanixReporting.js#L91

running `npm run serve` or `yarn run serve` will open a browser that will not load the development plugin as the url in the params is not existing due to the double encoding.

Original:
https://localhost:8080

Wrong:
https%253A%252F%252Flocalhost%253A8080 
-> decoded (with decodeURIComponent) https%3A%2F%2Flocalhost%3A8080
-> decoded again (with decodeURIComponent) https://localhost:8080

Working:
- https:%2F%2Flocalhost:8080
- https%3A%2F%2Flocalhost%3A8080
- the output of encodeURIComponent("https://localhost:8080") works too:
https%3A%2F%2Flocalhost%3A8080

**Comment by pauloramires** [comment]
The localhost url is not being encoded twice.  This url is passed unencoded [here](https://github.com/fazendadosoftware/vue-cli-plugin-leanix/blob/1599c7a9238b0e7d3093a24a98eda2542898f0b4/index.js#L49) and [here](https://github.com/fazendadosoftware/vue-cli-plugin-leanix/blob/1599c7a9238b0e7d3093a24a98eda2542898f0b4/commands/LeanixReporting.js#L26). The only encoding occurs [here](https://github.com/fazendadosoftware/vue-cli-plugin-leanix/blob/1599c7a9238b0e7d3093a24a98eda2542898f0b4/commands/LeanixReporting.js#L91) in order to include it as a query string argument or the launchUrl.

I was not able to reproduce the issue you reported. Running ```yarn serve``` or ```npm run serve``` does indeed open a new browser window pointing to the dev url within leanix. Which version of the vue-cli and vue-cli-plugin-leanix are you using?

**Comment by mrandi** [comment]
Hi, thx for the fast reply.
I created a branch here to show the issue: https://github.com/mrandi/leanix-bootstrap-report/tree/update-dep
After creating the `lxr.json` file, you should be able to reproduce the issue.

npm version: 6.7.0
vue version: 3.6.3
I'm using Chrome ` 73.0.3683.103` configured as followed:
- open a new tab and type in the url bar this `chrome://flags/#allow-insecure-localhost` activate the *Allow invalid certificates for resources loaded from localhost*.

**Comment by pauloramires** [comment]
Hi Michele, still did not managed to reproduce the error using your project.
On my computer the launch url is working as expected. Could you please update the vue-cli-plugin-leanix dependency to the latest version (0.2.0) and check if the error persists? Thanks

**Comment by mrandi** [comment]
Hi,
The project is already configured with the dependency you described.
Could be that you tested the master? I pushed only to the branch update-dep.
Thanks

Il giorno mar 23 apr 2019 alle 14:56 Paulo dos Santos <
notifications@github.com> ha scritto:

**Comment by pauloramires** [comment]
Nope, I've tested the update-dep branch. Moreover I've tried on a second machine using Ubuntu (on my other I was using Win10). After launch the dev server, the browser window opens us as expected. Are you able to switch your node environment (using nvm, for eg.) and run it on a vanilla node installation, so that we exclude that possibility (globally installed libraries, etc...)?

![Screenshot from 2019-04-25 08-59-28](https://user-images.githubusercontent.com/1428629/56734176-847b1880-6738-11e9-9456-29bd62b32bc9.png)

**Comment by mrandi** [comment]
@pauloramires I asked also a few colleague to test it, and seems to be a problem on my machine. I tried from a fresh env, but didn't help. I will figure it out but I will close the ticket. Thanks a lot for your support!
If I ever found the exact issue I will update the ticket. thx again!
